### ISSUE TITLE
[Insight] A Symfony application should be bootable

### ISSUE THREAD

**Issue by morozovalexander** [morozovalexander/symfocommerce#33]
> SymfonyInsight was not able to boot your Symfony application. If you need to customize files or run commands to make it bootable, you can edit your SymfonyInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service &quot;app.faker_provider&quot; has a dependency on a non-existent service &quot;nelmio_alice.faker.generator&quot;. in /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:32
Stack trace:
#0 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
#1 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(29): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#2 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(67): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Array)
#3 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(29): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#4 /home/foobar/code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Defini

**Comment by morozovalexander** [comment]
fixed

**Comment by openlife** [comment]
Please indicate how you fix it please.

**Comment by morozovalexander** [comment]
> Please indicate how you fix it please.

I don't remember it completely. It may be something like adding all dependencies in composer.json or fixing vendors versions

**Comment by NicoRiso13** [comment]
> 

pas terrible comme mentalité

**Comment by morozovalexander** [comment]
> > 
> 
> pas terrible comme mentalité

Can you describe what's wrong? You have the same errors? In this project?

**Comment by morozovalexander** [comment]
> > 
> 
> pas terrible comme mentalité

any details please?
